# 构建 静态 站点并将其部署到 GitHub Pages 的示例工作流程
name: 发布storybook&vitepress

on:
  # 在针对 `docs` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [ main ]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出main分支代码
        uses: actions/checkout@v4
        with:
          ref: main
          # 如果未启用 lastUpdated，则不需要
          fetch-depth: 0
      # 如果使用 pnpm，请取消此区域注释
      - name: 设置并安装指定pnpm版本
        uses: pnpm/action-setup@v3
        with:
          version: 9
      # end
      # 如果使用 Bun，请取消注释
      # - name: 设置并安装Bun
      #   uses: oven-sh/setup-bun@v1
      - name: 设置并安装指定node版本
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # 缓存依赖,npm / pnpm / yarn,根据pnpm-lock.yaml等其他文件
          # cache: pnpm
      - name: 配置页面
        uses: actions/configure-pages@v4
      - name: 下载依赖
        # npm ci / pnpm install / yarn install / bun install
        run: pnpm install
#      - name: 打包storybook
#        # npm run docs:build / pnpm docs:build / yarn docs:build / bun run docs:build
#        run: pnpm storybook:build
      - name: 打包vitepress
        # npm run docs:build / pnpm docs:build / yarn docs:build / bun run docs:build
        run: pnpm vitepress:build
      - name: 上传打包文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: |
        ${{ steps.deployment.outputs.page_url }}vitepress
    needs: build
    runs-on: ubuntu-latest
    name: 发布
    steps:
      - name: 发布到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # 重新推送数据到algolia
  algolia:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - name: 获取algolia配置
        id: algolia_config
        run: echo "config=$(cat algolia.json | jq -r tostring)" >> $GITHUB_OUTPUT
      - name: 推送indices到algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          API_KEY: ${{ secrets.ADMIN_API_KEY }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
